# Generated by Django 2.1.3 on 2018-12-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181223_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_solution',
        ),
        migrations.AddField(
            model_name='question',
            name='solution_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_answer', to='main.Answer'),
        ),
    ]
