version: '2'

services:

  django_mysql:
    image: mysql:5.7
    container_name: django_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
       - ./db/mysql:/var/lib/mysql
    ports:
      - "19001:3306"
    networks:
      - shared

  django_web:
    build: ./
    container_name: django_web
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    ports:
      - "9000:9000"
    environment:
      ENV: ${ENV}
      SECRET_KEY: ${SECRET_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    networks:
      - shared
    depends_on:
      - django_mysql

networks:
  shared:
    driver: bridge
